source .env
PGPASSWORD=$DATABASE_PASSWORD psql -h 127.0.0.1 -U ${DATABASE_USER} -c "DROP DATABASE IF EXISTS ${APPLICATION_DATABASE_NAME};"
PGPASSWORD=$DATABASE_PASSWORD psql -h 127.0.0.1 -U ${DATABASE_USER} -c "CREATE DATABASE ${APPLICATION_DATABASE_NAME};"
PGPASSWORD=$DATABASE_PASSWORD psql -h 127.0.0.1 -U ${DATABASE_USER} ${APPLICATION_DATABASE_NAME} < schema.sql
