source .env
PGPASSWORD=$DATABASE_PASSWORD psql -h 127.0.0.1 -U ${DATABASE_USER} -c "DROP DATABASE IF EXISTS ${DATABASE_ENV_NAME};"
PGPASSWORD=$DATABASE_PASSWORD psql -h 127.0.0.1 -U ${DATABASE_USER} -c "CREATE DATABASE ${DATABASE_ENV_NAME};"
PGPASSWORD=$DATABASE_PASSWORD psql -h 127.0.0.1 -U ${DATABASE_USER} ${DATABASE_ENV_NAME} < schema.sql
